#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

# Navigate to source code root.
cd "$(dirname "$0")/.."

echo "Tests started at…"
date "+%H:%M:%S"

# Check if NPM is installed
if command -v npm >/dev/null 2>&1; then
  script/setup

  echo "Running tests…"
  date "+%H:%M:%S"

  script/test
else
  echo "==> NPM must be installed. Aborting."
fi
