#!/bin/bash

# script/server: Launch the application and any extra required processes
#                locally.

# Exit immediately if a command exits with a non-zero status
set -e

# Store a local variable of the scripts current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if NPM is installed
if command -v npm >/dev/null 2>&1; then
  ${DIR}/update

  echo "==> Launching application..."
  ionic serve
else
  echo "==> NPM must be installed. Aborting."
fi
