#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

# Navigate to source code root.
cd "$(dirname "$0")/.."

# Check if NPM is installed
if command -v npm >/dev/null 2>&1; then
  script/bootstrap

  echo '==> Cleaning project...'
  npm run clean
else
  echo "==> NPM must be installed."
fi

echo "==> App is now ready to go!"
