#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

# Exit immediately if a command exits with a non-zero status
set -e

# Store a local variable of the scripts current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if NPM is installed
if command -v npm >/dev/null 2>&1; then
  ${DIR}/bootstrap

  echo '==> Cleaning project...'
  npm run clean
else
  echo "==> NPM must be installed."
fi

echo "==> App is now ready to go!"
