#!/bin/bash

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

# Exit immediately if a command exits with a non-zero status
set -e

# Store a local variable of the scripts current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if NPM is installed
if command -v npm >/dev/null 2>&1; then
  ${DIR}/update

  echo "==> Running tests..."
  npm test
else
  echo "==> NPM must be installed. Aborting."
fi
